groups/urls.py
from django.conf.urls import url
from . import views


app_name = 'groups'

urlpatterns = [
    url(r'^$', views.ListGroups.as_view(), name='all'),
    url(r'new/$', views.CreateGroup.as_view(), name='create'),
    url(r'posts/in/(?P<slug>[-\w]+)/$', views.SingleGroup.as_view(), name='single'),
    url(r'update/(?P<pk>\d+)/$', views.UpdateGroup.as_view(), name='update'),
    url(r'join/(?P<slug>[-\w]+)/$', views.JoinGroup.as_view(), name='join'),
    url(r'leave/(?P<slug>[-\w]+)/$', views.LeaveGroup.as_view(), name='leave'),
]

# urlpatterns = [
#     url(r"^$", views.ListGroups.as_view(), name="all"),
#     url(r"^new/$", views.CreateGroup.as_view(), name="create"),
#     url(r"^posts/in/(?P<slug>[-\w]+)/$",views.SingleGroup.as_view(),name="single"),
#     url(r"join/(?P<slug>[-\w]+)/$",views.JoinGroup.as_view(),name="join"),
#     url(r"leave/(?P<slug>[-\w]+)/$",views.LeaveGroup.as_view(),name="leave"),
# ]

posts/urls.py
from django.conf.urls import url
from . import views
from django_filters.views import FilterView
from .filters import PostFilter

app_name = 'posts'

urlpatterns = [
    url(r'^$', views.PostList.as_view(), name='all'),
    url(r'new/$', views.CreatePost.as_view(), name='create'),
    url(r'by/(?P<username>[-\w]+)/$', views.UserPosts.as_view(), name='for_user'),
    url(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.PostDetail.as_view(), name='single'),
    url(r'update/(?P<pk>\d+)/$', views.UpdatePost.as_view(), name='update'),
    url(r'delete/(?P<pk>\d+)/$', views.DeletePost.as_view(), name='delete'),
    # url(r'^search/$', FilterView.as_view(filterset_class=PostFilter,
    #                                      template_name='posts/post_search.html'), name='search'),
    url(r'^search/$', views.search, name='search')
]

social/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

from . import views
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    # url(r'^$', auth_views.LoginView.as_view(template_name='accounts/login.html'),
    #    name='home_login'),
    url(r'^test/$', views.TestPage.as_view(), name='test'),
    # url(r'^test/$', views.HomePage.as_view(), name='test'),
    # url(r'^test/$', RedirectView.as_view(url='http://127.0.0.1:8000/'), name='test'),
    url(r'^thanks/$', views.ThanksPage.as_view(), name='thanks'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^groups/', include('groups.urls', namespace='groups')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

groups/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.text import slugify
import misaka
from django.contrib.auth import get_user_model
from django import template
from accounts.models import User


# Create your models here.
AuthUser = get_user_model()
# AuthUser = User
register = template.Library()


class Group(models.Model):
    image_url = models.URLField(default="http://via.placeholder.com/200x200")
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, blank=True, default='')
    members = models.ManyToManyField(AuthUser, related_name='group_members', through='GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'slug':self.slug})

    class Meta:
        ordering = ['name']


class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name='memberships')
    user = models.ForeignKey(AuthUser, related_name='user_group')

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group', 'user')

groups/views.py
from django.shortcuts import get_object_or_404, render
from django.contrib import messages
from django.db import IntegrityError

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.urlresolvers import reverse
from django.views import generic
from groups.models import Group, GroupMember
from . import models


# Create your views here.
class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ('image_url', 'name', 'description')
    model = Group


class UpdateGroup(LoginRequiredMixin, generic.UpdateView):
    fields = ('image_url', 'name', 'description')
    model = Group
    template_name_suffix = '_update_form'

    def get_object(self, *args, **kwargs):
        group = get_object_or_404(self.model, pk=self.kwargs['pk'])
        return group


class SingleGroup(generic.DetailView):
    model = Group


class ListGroups(generic.ListView):
    model = Group


class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        # return reverse('groups:single', kwargs={'slug': self.kwargs.get('slug')})
        return reverse('groups:all')

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user, group=group)
        except IntegrityError:
            messages.warning(self.request, 'Warning already a member!')
        else:
            messages.success(self.request, 'You are now a member!')

        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        # return reverse('groups:single', kwargs={'slug': self.kwargs.get('slug')})
        return reverse('groups:all')

    def get(self, request, *args, **kwargs):

        try:
            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get('slug')
            ).get()
        except models.GroupMember.DoesNotExist:
            messages.warning(self.request, 'Sorry you are not in this group!')
        else:
            membership.delete()
            messages.success(self.request, 'You have left the group!')
        return super().get(request, *args, **kwargs)

groups/templates/groups/_group.html
<div class="thumbnail col-sm-6 col-md-4 grid-item" style="padding: 15px; margin: 0px">
    <a class="" href="{% url 'groups:single' slug=group.slug %}">
        <img src={{ group.image_url }}>
    </a>
    <div class="caption">
        <!--
            <a class="list-group-item img-responsive" href="{#% url 'groups:single' slug=group.slug %#}">
            -->
        <a class="" href="{% url 'groups:single' slug=group.slug %}">
            <h4>{{ group.name }}</h4>
        </a>
        <p>{{ group.description_html|safe|truncatechars_html:85 }}</p>
        <div class="">
            <span class="badge">{{ group.members.count }} </span>
            member{{ group.members.count|pluralize }}
            <span class="badge">{{ group.posts.count }} </span>
            post{{ group.posts.count|pluralize }}
        </div>
        <h5 class="media-body">
            {% if request.user.is_authenticated and request.user.id == user.id %}
                {% if request.user in group.members.all %}
                    <div class="" style="float: right;">
                        <a href="{% url 'groups:leave' slug=group.slug %}" title="leave"
                           class="btn">
                            <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
                            <span class="text-danger icon-label">Leave</span>
                        </a>
                    </div>
                {% else %}
                    <div class="" style="float: right;">
                        <a href="{% url 'groups:join' slug=group.slug %}" title="join"
                           class="btn">
                            <span class="glyphicon glyphicon-ok text-success" aria-hidden="true"></span>
                            <span class="text-success icon-label">Join</span>
                        </a>
                    </div>
                {% endif %}
            {% endif %}
        </h5>
    </div>
</div>

groups/templates/groups/group_base.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            {% if request.user.is_authenticated %}
                {% block pregroup %} {% endblock %}
            {% endif %}
        </div>
    </div>
    <div class="container">
        <div class="row">
            {% if request.user.is_authenticated %}
                {% block group_content %} {% endblock %}
            {% endif %}
        </div>
    </div>
    <div class="container">
        <div class="row">
            {% if request.user.is_authenticated %}
                {% block postgroup %} {% endblock %}
            {% endif %}
        </div>
    </div>
{% endblock %}

groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
    <!--
    <div class="col-sm-6 col-sm-offset-2 col-md-4 col-md-offset-4" style="padding-top: 10px">
    -->
        {% include "groups/_group.html" %}
    <!--
    <div>
    -->
{% endblock %}

{% block group_content %}
<!--
<div class="col-md-8">
-->
<div class="container">
    <h3>Posts</h3>
    {% if group.posts.count == 0 %}
        <h2>No posts in this group yet!</h2>
    {% else %}
        {% for post in group.posts.all %}
            {% include "posts/_post.html" %}
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap3 %}

{% block group_content %}
<div class="col-sm-6 col-sm-offset-2 col-md-4 col-md-offset-4" style="padding-top: 10px">
    <h4>New Group</h4>
    <form id="groupForm" action="{% url 'groups:create' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Create" class="btn btn-primary btn-default">
        <a href="{% url 'groups:all' %}"
           class="btn btn-simple btn-default">Cancel</a>
    </form>
</div>
{% endblock %}

groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}
{% block pregroup %}
    {% if user.is_authenticated %}
    {% endif %}
    <div class="content">
    <!--
        <h3 class="center-div" style="padding-top: 10px">Welcome to the group page!</h3><br>
    -->
    </div>
{% endblock %}

{% block group_content %}
    <!-- <div class="list-group row"> -->
    <div class="list-group">
        {% for group in object_list %}
            {% include "groups/_group.html" %}
        {% endfor %}
    </div>


<div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <img src="" class="imagepreview" style="width: 100%;">
            </div>
        </div>
    </div>
</div>
{% endblock %}

groups/templates/groups/group_update_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap3 %}

{% block group_content %}
<div class="col-sm-6 col-sm-offset-2 col-md-4 col-md-offset-4">
    <h4>Update Group</h4>
    <form id="postForm" action="{% url 'groups:update' pk=group.pk %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Update" class="btn btn-primary btn-default">
        <a href="{% url 'groups:single' slug=group.slug %}"
           class="btn btn-simple btn-default">Cancel</a>
    </form>
</div>
{% endblock %}