accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'login/$',
        auth_views.LoginView.as_view(template_name='accounts/login.html'),
        name='login'),
    url(r'logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'signup/$', views.SignUp.as_view(), name='signup'),
    url(r'all/$', views.ListAccount.as_view(), name='all'),
    url(r'detail/(?P<pk>\d+)/$', views.DetailAccount.as_view(), name='detail'),
]

posts/urls.py
from django.conf.urls import url
from . import views
from django_filters.views import FilterView
from .filters import PostFilter

app_name = 'posts'

urlpatterns = [
    url(r'^$', views.PostList.as_view(), name='all'),
    url(r'new/$', views.CreatePost.as_view(), name='create'),
    url(r'by/(?P<username>[-\w]+)/$', views.UserPosts.as_view(), name='for_user'),
    url(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.PostDetail.as_view(), name='single'),
    url(r'update/(?P<pk>\d+)/$', views.UpdatePost.as_view(), name='update'),
    url(r'delete/(?P<pk>\d+)/$', views.DeletePost.as_view(), name='delete'),
    # url(r'^search/$', FilterView.as_view(filterset_class=PostFilter,
    #                                      template_name='posts/post_search.html'), name='search'),
    url(r'^search/$', views.search, name='search')
]

social/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

from . import views
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    # url(r'^$', auth_views.LoginView.as_view(template_name='accounts/login.html'),
    #    name='home_login'),
    url(r'^test/$', views.TestPage.as_view(), name='test'),
    # url(r'^test/$', views.HomePage.as_view(), name='test'),
    # url(r'^test/$', RedirectView.as_view(url='http://127.0.0.1:8000/'), name='test'),
    url(r'^thanks/$', views.ThanksPage.as_view(), name='thanks'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^groups/', include('groups.urls', namespace='groups')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- bootstrap 4.0
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    -->

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
            integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
            crossorigin="anonymous"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>

    <script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script>
    <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'social/css/master.css' %}">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">

    <link rel="shortcut icon" href="{% static 'favicon/favicon-96x96.png' %}"/>

    <title>Social-Group-Django</title>
</head>
<body id="home-body" class="" style="padding-top: 50px">
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#example-navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'posts:search' %}">
                Home
            </a>

        </div>
        <div class="collapse navbar-collapse" id="example-navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <ul class="nav navbar-nav">
                    {% if request.user.is_authenticated %}
                        <li><a href="{% url 'posts:search' %}"><span class="glyphicon glyphicon-search"></span></a></li>
                        <li><a href="{% url 'accounts:detail' pk=request.user.id %}"><span
                                class="glyphicon glyphicon-user"></span></a></li>
                        <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">All<span
                                class="caret"></span></a>
                            <ul class="dropdown-menu navbar-inverse">
                                <li><a style="color: #337ab7" href="{% url 'posts:all' %}">Posts</a></li>
                                <li><a style="color: #337ab7" href="{% url 'groups:all' %}">Groups</a></li>
                                <li><a style="color: #337ab7" href="{% url 'accounts:all' %}">Users</a></li>
                            </ul>
                        <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Create<span
                                class="caret"></span></a>
                            <ul class="dropdown-menu navbar-inverse">
                                <li><a style="color: #337ab7" href="{% url 'posts:create' %}">Post</a></li>
                                <li><a style="color: #337ab7" href="{% url 'groups:create' %}">Group</a></li>
                            </ul>
                        <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
                    {% else %}
                        <li><a href="{% url 'accounts:login' %}">Log In</a></li>
                        <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
                    {% endif %}

                </ul>
            </ul>
        </div>
    </div>
</nav>

{% block profile_page %}
{% endblock %}

<!-- <div class="container mycontent" style="overflow-y: scroll; height: 95vh; width: 100%"> -->
<div class="container mycontent">
    {% block content %}
    {% endblock %}
</div>
<!-- need to comment out, for using modal pop-up
    <script src="{#% static 'social/js/jquery-3.1.1.min.js' %#}"></script>
    -->
<script src="{% static 'social/js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'social/js/infinite.min.js' %}"></script>
<script type="text/javascript" src="{% static 'social/js/master.js' %}"></script>

{% block javascript %}
{% endblock %}
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
    <h1 class="home-text">Share you favorites with others!</h1>
{% endblock %}

templates/test.html
{% extends "base.html" %}
{% if request.user.is_authenticated and request.user.id == user.id %}
    {% block content %}
        <h1 class="home-text">Hi {{ user.username }}! Welcome back!</h1>
    {% endblock %}
{% endif %}

templates/thanks.html
{% extends "base.html" %}
{% if request.user.is_authenticated and request.user.id == user.id %}
    {% block content %}
        <h1 class="home-text">Thanks for visiting! See you soon!</h1>
    {% endblock %}
{% endif %}