accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'login/$',
        auth_views.LoginView.as_view(template_name='accounts/login.html'),
        name='login'),
    url(r'logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'signup/$', views.SignUp.as_view(), name='signup'),
    url(r'all/$', views.ListAccount.as_view(), name='all'),
    url(r'detail/(?P<pk>\d+)/$', views.DetailAccount.as_view(), name='detail'),
]

posts/urls.py
from django.conf.urls import url
from . import views
from django_filters.views import FilterView
from .filters import PostFilter

app_name = 'posts'

urlpatterns = [
    url(r'^$', views.PostList.as_view(), name='all'),
    url(r'new/$', views.CreatePost.as_view(), name='create'),
    url(r'by/(?P<username>[-\w]+)/$', views.UserPosts.as_view(), name='for_user'),
    url(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.PostDetail.as_view(), name='single'),
    url(r'update/(?P<pk>\d+)/$', views.UpdatePost.as_view(), name='update'),
    url(r'delete/(?P<pk>\d+)/$', views.DeletePost.as_view(), name='delete'),
    # url(r'^search/$', FilterView.as_view(filterset_class=PostFilter,
    #                                      template_name='posts/post_search.html'), name='search'),
    url(r'^search/$', views.search, name='search')
]

social/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

from . import views
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    # url(r'^$', auth_views.LoginView.as_view(template_name='accounts/login.html'),
    #    name='home_login'),
    url(r'^test/$', views.TestPage.as_view(), name='test'),
    # url(r'^test/$', views.HomePage.as_view(), name='test'),
    # url(r'^test/$', RedirectView.as_view(url='http://127.0.0.1:8000/'), name='test'),
    url(r'^thanks/$', views.ThanksPage.as_view(), name='thanks'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^groups/', include('groups.urls', namespace='groups')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

posts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings
from groups.models import Group
from accounts.models import User
from django.contrib.auth import get_user_model

import misaka

# Create your models here.
AuthUser = get_user_model()
# AuthUser = User


class Post(models.Model):
    image_url = models.URLField(default="http://via.placeholder.com/200x200")
    user = models.ForeignKey(AuthUser, related_name='posts')
    created_at = models.DateTimeField(auto_now=True)
    # image = models.ImageField(upload_to='documents/')
    # image_url = models.URLField()
    # image_url = models.TextField()
    message = models.TextField(blank=True, default="")
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name='posts', null=True, blank=True)
    postlike_members = models.ManyToManyField(AuthUser, related_name='postlike_members', through='PostLike')

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:single', kwargs={'username': self.user.username,
                                               'pk': self.pk})

    class Meta:
        ordering = ['-created_at']
        unique_together = ['user', 'message']


class PostLike(models.Model):
    post = models.ForeignKey(Post, related_name='post_liked')
    user = models.ForeignKey(AuthUser, related_name='user_like')

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('post', 'user')

posts/forms.py
from django import forms

from posts import models


class PostForm(forms.ModelForm):
    class Meta:
        # fields = ("image", "message", "group")
        fields = ("image_url", "message", "group")
        model = models.Post

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if user is not None:
            self.fields["group"].queryset = (
                models.Group.objects.filter(
                    pk__in=user.groups.values_list("group__pk")
                )
            )

posts/views.py
from django.contrib import messages

from django.shortcuts import render, get_object_or_404, render_to_response
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.template import RequestContext

from django.http import Http404
from django.views import generic
from django.db.models import Q

from braces.views import SelectRelatedMixin

from . import models
from . import forms
from .filters import PostFilter

from django.contrib.auth import get_user_model
User = get_user_model()


def search(request):
    if request.method == 'GET':
        in_text = request.GET.get('in_text', '')
        try:
            status = models.Post.objects.filter(Q(message__icontains=in_text) |
                                                Q(user__username__icontains=in_text) |
                                                Q(group__name__icontains=in_text))
        except models.Post.DoesNotExist:
            raise Http404
        else:
            return render(request, "posts/post_search.html", {"posts": status})
    else:
        return render(request, "posts/post_search.html", {})


# Create your views here.
class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    # paginate_by = 5
    context_object_name = 'posts'
    select_related = ('user', 'group')


class UserPosts(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context


class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    # form_class = forms.PostForm
    # fields = ('image', 'message', 'group')
    fields = ('image_url', 'message', 'group')
    model = models.Post

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class UpdatePost(LoginRequiredMixin, SelectRelatedMixin, generic.UpdateView):
    fields = ('image_url', 'message', 'group')
    model = models.Post
    template_name_suffix = '_update_form'

    def get_object(self, *args, **kwargs):
        post = get_object_or_404(self.model, pk=self.kwargs['pk'])
        return post


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Post Deleted')
        return super().delete(*args, **kwargs)

posts/templates/posts/_post.html
<div class="media thumbnail col-sm-6 col-md-3 transparent-padding grid-item">
	<div class="media-heading">
        <a class="pop" href="#">
            <img class="thumbnail" style="width: 100%;display: block; margin: 0 auto;" src={{ post.image_url }}>
        </a>
        <p>
        <h4 class="media-body center-div"> {{ post.message_html|safe|truncatechars_html:80 }}
        </h4>
        </p>
        <span class="username">
            <a href="{% url 'accounts:detail' pk=post.user.id %}">@{{ post.user.username }}</a>
            <!-- <a href="{#% url 'posts:for_user' username=post.user.username %#}">@{#{ post.user.username }#}</a> -->
        </span>
        {% if post.group %}
            <span class="group-name"> posted in group
                <a href="{% url 'groups:single' slug=post.group.slug %}">{{ post.group.name }}</a>
            </span>
        {% endif %}
        <span class="time-name"> at
            <time class="time">
                <a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_at }}</a>
            </time>
            </span>
        <h5 class="media-body">
            {% if request.user.is_authenticated and request.user.id == user.id %}
                {% if user.is_authenticated and post.user.id == user.id and not hide_delete %}
                    <div style="float: right">
                        <a href="{% url 'posts:update' pk=post.pk %}" title="update" class="btn">
                            <span class="glyphicon glyphicon-edit text-warning" aria-hidden="true"></span>
                            <span class="text-warning icon-label">Edit</span>
                        </a>
                        <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn">
                            <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
                            <span class="text-danger icon-label">Delete</span>
                        </a>
                    </div>
                {% endif %}
            {% endif %}
        </h5>
	</div>
</div>

<div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>

                <!--
                 <img src="" class="imagepreview displayed" style="width: 100%; ">
                 -->
                <img src="" class="imagepreview displayed" style="max-width: 100%; max-height: 90vh; height: auto;">
            </div>
        </div>
    </div>
</div>

posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="" style="margin: 0 auto">
            {% if user.is_authenticated %}
                {% block pre_post_content %}{% endblock %}
            {% endif %}
        </div>
    </div>
    <div class="container">
        <div class="row">
            {% if user.is_authenticated %}
                {% block post_content %}{% endblock %}
            {% endif %}
        </div>
    </div>
    <div class="container">
        <div class="row">
            {% if user.is_authenticated %}
                {% block post_post %}{% endblock %}
            {% endif %}
        </div>
    </div>
{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}

{% block post_content %}
    <div class="" style="">
{% include "posts/_post.html" with post=object hide_delete=True%}
    </div>
{% endblock %}

{% block post_post %}
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Confirm Delete" class="btn btn-danger btn-default">
        <a href="{% url 'posts:single' username=user.username pk=object.pk %}"
           class="btn btn-simple btn-default">Cancel</a>
                    <div style="float: right">
                        <a href="{% url 'posts:update' pk=post.pk %}" title="update" class="btn btn-simple">
                            <span class="glyphicon glyphicon-edit text-info" aria-hidden="true"></span>
                            <span class="text-info icon-label">Edit</span>
                        </a>
                        <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
                            <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
                            <span class="text-danger icon-label">Delete</span>
                        </a>
                    </div>
    </form>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block post_content %}
    {% include "posts/_post.html" %}
{% endblock %}

posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}
{% load bootstrap3 %}

{% block post_content %}
<div class="col-sm-6 col-sm-offset-2 col-md-4 col-md-offset-4" style="padding-top: 10px">
    <h4>New Post</h4>
    <form id="postForm" action="{% url 'posts:create' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Create" class="btn btn-primary btn-default">
        <a href="{% url 'posts:all' %}"
           class="btn btn-simple btn-default">Cancel</a>
    </form>
</div>
{% endblock %}

posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}

{% block pre_post_content %}
{% endblock %}

{% block post_content %}
    {% if user.is_authenticated %}
    {% for post in posts %}
        {% include "posts/_post.html"%}
    {% endfor %}
    {% endif %}
{% endblock %}

posts/templates/posts/post_search.html
{% extends "posts/post_base.html" %}

{% block pre_post_content %}
    <!--
    <div class="col-sm-offset-3 col-md-offset-4 col-md-6">
    -->
        <form name="myform" method="GET" action="{% url 'posts:search' %}" class="form-row form-inline"
              role="search" style="text-align: center;">
                <!-- <div class="form-group" style="text-align: center; width: 50%; margin: 0 auto"> -->
                <div class="form-group center-div">
                    <input type="text" name="in_text" class="form-control" placeholder="Search">
                    <button type="submit" class="btn btn-default">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </div>
        </form>
    <!--
    </div>
    -->
{% endblock %}

{% block post_content %}

    <!--
    <form method="get" action="{#% url 'posts:search' %#}">
    <p>Filter: <input style="background-color: black" type="text" value="3" name="filter"/></p>
    <p><input type="submit" name="submit" value="submit"/></p>
    </form>
    -->
    {% for post in posts %}
        {% include "posts/_post.html" %}
    {% endfor %}
{% endblock %}

posts/templates/posts/post_update_form.html
{% extends "posts/post_base.html" %}
{% load bootstrap3 %}

{% block post_content %}
<div class="col-sm-6 col-sm-offset-2 col-md-4 col-md-offset-4">
    <h4>Update Post</h4>
    <form id="postForm" action="{% url 'posts:update' pk=post.pk %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Update" class="btn btn-primary btn-default">
        <a href="{% url 'posts:single' username=user.username pk=object.pk %}"
           class="btn btn-simple btn-default">Cancel</a>
    </form>
</div>
{% endblock %}

posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

    {% block pre_post_content %}
        {% if request.user.is_authenticated %}
            <div class="card card-with-shadow">
                <div class="content">
                    <h5 class="title">Groups</h5>
                    <ul class="list-unstyled">
                        {% for group in post_user.group_members.all %}
                            <li class="group li-with-bullet">
                                <a href="{% url 'groups:single' slug=group.slug %}"> {{ group.name }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endif %}
    {% endblock %}

    {% block post_content %}
        {% if request.user.is_authenticated %}
        {% for post in post_list %}
            {% include "posts/_post.html" %}
        {% endfor %}
        {% endif %}
    {% endblock %}